### ISSUE TITLE
Bug in the experiments?

### ISSUE THREAD

**Issue by RAMitchell** [aldolipani/OwenShap#1]
@aldolipani Thank you for making this work available.

I think there is a mistake here where Castro sampling needs only half as many samples. Here (https://github.com/aldolipani/OwenShap/blob/976eb5e378fa820f71c4d794f90a0295b7614390/shaps.py#L97) where the model is evaluated with the feature on and off, evaluation from the previous iteration inside a permutation can be reused.

Considering this, Castro sampling requires half the samples as presented in this work and seems roughly equivalent in accuracy to Owen sampling, although the Owen-Halved version does seem slightly better than Castro in my experiment.

**Comment by aldolipani** [comment]
@RAMitchell can you propose a fix for that line of code? This would help me understand your claim better.

I think you are referring to another implementation of the Castro sampling algorithm. However, this is an equivalent implementation that does not need the caching of the results. In this paper, we decided to go for this version because:
1. The template of the algorithm is similar to the one used by the Owen ones making their comparison easier. All the algorithms have two main loops: the first loop to calculate the samples and the second loop to compute the shapely values.  
2. The other implementation, the one with the caching you are referring to, turns out to be slower than our version. I believe that this happens because, in our version of the algorithm, the sampling is performed using NumPy and the model inference is performed using batching, which combination makes this version faster than the original one.
